;/*FB_PKG_DELIM*/

__d("ClickToMessagingAdsAdoptionLoggingFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("6643"),s=o("FalcoLoggerInternal").create("click_to_messaging_ads_adoption_logging",e),u=s;l.default=u}),98);
__d("CometFeedSection.react",["FDSUnitHeader.react","react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){var t=o("react-compiler-runtime").c(10),n=e.meta,a=e.sectionContents,i=e.title,l=e.widthStyle,u=l===void 0?"none":l,c;t[0]!==u?(c={0:{},1:{className:"xh8yej3"}}[(u==="full")<<0],t[0]=u,t[1]=c):c=t[1];var d;t[2]===Symbol.for("react.memo_cache_sentinel")?(d={className:"xd9ej83 x162z183 xsag5q8"},t[2]=d):d=t[2];var m;t[3]!==n||t[4]!==i?(m=s.jsx("div",babelHelpers.extends({},d,{children:s.jsx(r("FDSUnitHeader.react"),{headline:i,headlineColor:"secondary",level:4,meta:n})})),t[3]=n,t[4]=i,t[5]=m):m=t[5];var p;return t[6]!==a||t[7]!==c||t[8]!==m?(p=s.jsxs("div",babelHelpers.extends({},c,{"data-testid":void 0,role:"feed",children:[m,a]})),t[6]=a,t[7]=c,t[8]=m,t[9]=p):p=t[9],p}l.default=u}),98);
__d("CometPageAdminCTWAEventLoggingUtils",["react","react-compiler-runtime","requireDeferred","useSinglePartialViewImpression"],(function(t,n,r,o,a,i,l){"use strict";var e,s=(e||(e=o("react"))).useCallback,u=r("requireDeferred")("ClickToWhatsAppBusinessDownloadFalcoEvent").__setRef("CometPageAdminCTWAEventLoggingUtils");function c(e,t,n,r,o){u.onReady(function(a){a.log(function(){return babelHelpers.extends({event:n,event_location:t,page_id:e,ref:r},o)})})}function d(e,t,n){var a=o("react-compiler-runtime").c(6),i;a[0]!==t||a[1]!==e||a[2]!==n?(i=function(){c(e,t,"impression",n)},a[0]=t,a[1]=e,a[2]=n,a[3]=i):i=a[3];var l=i,s;return a[4]!==l?(s={onImpressionStart:l},a[4]=l,a[5]=s):s=a[5],r("useSinglePartialViewImpression")(s)}l.logCTWAEvent=c,l.useCTWAImpressionViewLogging=d}),98);
__d("FDSAppInstagramFilled16Icon",["cr:14328"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14328")}),98);
__d("FDSAppMessengerFilled16Icon",["cr:14340"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14340")}),98);
__d("FDSAppMessengerFilled16PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("505616"),16),u=e;l.default=u}),98);
__d("FDSAppWhatsappFilled16Icon",["cr:13939"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:13939")}),98);
__d("FDSInfoCircleFilled16Icon",["cr:14037"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14037")}),98);
__d("FDSInfoCircleFilled16PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("479176"),16),u=e;l.default=u}),98);
__d("FDSPushpinFilled16Icon",["cr:15538"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:15538")}),98);
__d("XCometProdashCometV2CommentsManagerControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/professional_dashboard/engagement/comments_manager/",Object.freeze({tab:"your_posts",filter:"all"}),void 0),s=e;l.default=s}),98);
__d("XCometProdashCometV2ContentLibraryControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/professional_dashboard/content/content_library/",Object.freeze({}),void 0),s=e;l.default=s}),98);