;/*FB_PKG_DELIM*/

__d("FDSGlobeAmericasFilled20Icon",["cr:13839"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:13839")}),98);
__d("FDSGlobeAmericasFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("560120"),20),u=e;l.default=u}),98);
__d("FDSPrivacyFilled20Icon",["cr:14071"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14071")}),98);
__d("FDSPrivacyFilled20PNGIcon.react",["ix","fbicon"],(function(t,n,r,o,a,i,l,s){"use strict";var e=o("fbicon")._(s("497245"),20),u=e;l.default=u}),98);
__d("ProfileCometEngagementLoggingContext",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.createContext({});l.default=u}),98);
__d("ProfileCometUtils",[],(function(t,n,r,o,a,i){"use strict";function e(e,t){return e!=null&&t!=null&&e===t}function l(t,n){return t==null||e(t,n)}i.isViewingSelfProfile=e,i.isViewingFeed=l}),66);
__d("ProfileEngagementEventsFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("1962347"),s=o("FalcoLoggerInternal").create("profile_engagement_events",e),u=s;l.default=u}),98);
__d("ProfilePlusAdminActivitiesFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("1794610"),s=o("FalcoLoggerInternal").create("profile_plus_admin_activities",e),u=s;l.default=u}),98);
__d("ProfilePlusIntentBasedSwitchingDialogQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="25010109362004033"}),null);
__d("ProfilePlusIntentBasedSwitchingDialogQuery$Parameters",["ProfilePlusIntentBasedSwitchingDialogQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("ProfilePlusIntentBasedSwitchingDialogQuery_facebookRelayOperation"),metadata:{},name:"ProfilePlusIntentBasedSwitchingDialogQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("ProfilePlusIntentBasedSwitchingDialog.entrypoint",["JSResourceForInteraction","ProfilePlusIntentBasedSwitchingDialogQuery$Parameters"],(function(t,n,r,o,a,i,l){"use strict";var e=r("JSResourceForInteraction")("ProfilePlusIntentBasedSwitchingDialog.react").__setRef("ProfilePlusIntentBasedSwitchingDialog.entrypoint"),s={getPreloadProps:function(t){return{queries:{queryReference:{options:{fetchPolicy:"network-only"},parameters:r("ProfilePlusIntentBasedSwitchingDialogQuery$Parameters"),variables:{profileID:t.routeParams.id,queryAllEligibleProfiles:t.otherParams.queryAllEligibleProfiles}}}}},root:e},u=s;l.default=u}),98);
__d("getRoundedCorners",[],(function(t,n,r,o,a,i){"use strict";var e={TOP_START:1,TOP_END:2,BOTTOM_START:4,BOTTOM_END:8,NONE:0,ALL:15};function l(e,t){return(e&t)===t}function s(t,n){if(t===0)return{};var r={},o=function(t,n){var e;r[t]=((e=r[t])!=null?e:0)|n};o(0,e.TOP_START),o(Math.min(n,t)-1,e.TOP_END);var a=t-(t%n===0?n:t%n);return o(a,e.BOTTOM_START),o(Math.min(a+n,t)-1,e.BOTTOM_END),t%n!==0&&a>=n&&o(a-1,e.BOTTOM_END),r}s.hasCorner=l,s.CORNERS=e,i.default=s}),66);
__d("useProfileCometEngagementEventsClickWithDataCallback",["FBLogger","ProfileCometContext","ProfileCometSession","ProfileEngagementEventsFalcoEvent","react","react-compiler-runtime","useCurrentRoute"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.useCallback,c=s.useContext;function d(){var e=o("react-compiler-runtime").c(3),t=c(r("ProfileCometContext")),n=t.profileID,a=r("useCurrentRoute")();n==null&&r("FBLogger")("profile_comet").mustfix("viewer id is a required field for profile engagement events logging");var i;return e[0]!==n||e[1]!==a?(i=function(t){r("ProfileEngagementEventsFalcoEvent").log(function(){return babelHelpers.extends({},t,{event_type:"click",profile_session_id:o("ProfileCometSession").get(n,a),viewee_userid_str:n})})},e[0]=n,e[1]=a,e[2]=i):i=e[2],i}l.default=d}),98);
__d("useProfileCometEngagementEventsClickCallback",["react","react-compiler-runtime","useProfileCometEngagementEventsClickWithDataCallback"],(function(t,n,r,o,a,i,l){"use strict";var e,s=(e||(e=o("react"))).useCallback;function u(e){var t=o("react-compiler-runtime").c(3),n=r("useProfileCometEngagementEventsClickWithDataCallback")(),a;return t[0]!==e||t[1]!==n?(a=function(){n(e)},t[0]=e,t[1]=n,t[2]=a):a=t[2],a}l.default=u}),98);
__d("useProfileCometEngagementEventsImpression",["FBLogger","ProfileCometContext","ProfileCometSession","ProfileEngagementEventsFalcoEvent","react","react-compiler-runtime","useCurrentRoute","useSinglePartialViewImpression"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.useCallback,c=s.useContext;function d(e){var t=o("react-compiler-runtime").c(9),n=c(r("ProfileCometContext")),a=n.profileID,i=r("useCurrentRoute")();a==null&&r("FBLogger")("profile_comet").mustfix("profile id is a required field for profile engagement events logging");var l;t[0]!==e?(l="impression",(e==null?void 0:e.event_type)!=null&&(l=e.event_type),t[0]=e,t[1]=l):l=t[1];var s;t[2]!==e||t[3]!==l||t[4]!==a||t[5]!==i?(s=function(){r("ProfileEngagementEventsFalcoEvent").log(function(){return babelHelpers.extends({},e,{event_type:l,profile_session_id:o("ProfileCometSession").get(a,i),viewee_userid:a})})},t[2]=e,t[3]=l,t[4]=a,t[5]=i,t[6]=s):s=t[6];var u=s,d;return t[7]!==u?(d={onImpressionStart:u},t[7]=u,t[8]=d):d=t[8],r("useSinglePartialViewImpression")(d)}l.default=d}),98);
__d("useProfileEngagementData",["FBLogger","ProfileCometContext","ProfileCometEngagementLoggingContext","ProfileCometSession","react","react-compiler-runtime","useCurrentRoute"],(function(t,n,r,o,a,i,l){"use strict";var e,s=(e||(e=o("react"))).useContext;function u(e){var t=o("react-compiler-runtime").c(8),n=s(r("ProfileCometContext")),a=s(r("ProfileCometEngagementLoggingContext")),i=r("useCurrentRoute")();if(n.profileID==="")return r("FBLogger")("profile_comet").mustfix("Tried to use Profile Engagement Logger without passing a profile ID via a ProfileCometContext provider."),null;var l=n.profileID,u;t[0]!==n.profileID||t[1]!==i?(u=o("ProfileCometSession").get(n.profileID,i),t[0]=n.profileID,t[1]=i,t[2]=u):u=t[2];var c;return t[3]!==e||t[4]!==a||t[5]!==n.profileID||t[6]!==u?(c=babelHelpers.extends({profile_id:l,profile_session_id:u},a,e),t[3]=e,t[4]=a,t[5]=n.profileID,t[6]=u,t[7]=c):c=t[7],c}l.default=u}),98);
__d("useProfileEngagementClickCallback",["FBLogger","react","react-compiler-runtime","requireDeferred","useProfileEngagementData"],(function(t,n,r,o,a,i,l){"use strict";var e,s=(e||(e=o("react"))).useCallback,u=r("requireDeferred")("ProfileEngagementFalcoEvent").__setRef("useProfileEngagementClickCallback");function c(e,t){var n,a=o("react-compiler-runtime").c(3),i=r("useProfileEngagementData")(e);i!=null&&((n=i)==null?void 0:n.profile_product_bucket)==null&&(r("FBLogger")("profile_comet").mustfix("product_bucket is a required field for profile engagement logging"),i=babelHelpers.extends({},i,{profile_product_bucket:"unknown"}));var l;return a[0]!==t||a[1]!==i?(l=function(n){if(i!=null){var e=babelHelpers.extends({profile_event_type:"click"},i);u.onReady(function(t){var n=t.log;n(function(){return e})})}t&&t(n)},a[0]=t,a[1]=i,a[2]=l):l=a[2],l}l.default=c}),98);
__d("useProfileEngagementImpression",["FBLogger","react","react-compiler-runtime","requireDeferred","useImpressionLogger","useProfileEngagementData"],(function(t,n,r,o,a,i,l){"use strict";var e,s=(e||(e=o("react"))).useCallback,u=r("requireDeferred")("ProfileEngagementFalcoEvent").__setRef("useProfileEngagementImpression");function c(e){var t=o("react-compiler-runtime").c(2),n=r("useProfileEngagementData")(e);(n==null?void 0:n.profile_product_bucket)==null&&r("FBLogger")("profile_comet").mustfix("profile_product_bucket is a required field for profile engagement logging"),(n==null?void 0:n.profile_surface)==null&&r("FBLogger")("profile_comet").mustfix("profile_surface is a required field for profile engagement logging");var a;t[0]!==n?(a=function(t){var e=t.log;if(n!=null){var r=babelHelpers.extends({profile_event_type:"impression",profile_product_bucket:"unknown",profile_surface:"unknown"},n);e(function(){return r})}},t[0]=n,t[1]=a):a=t[1];var i=a;return r("useImpressionLogger")(u,i)}l.default=c}),98);