;/*FB_PKG_DELIM*/

__d("CometUnifiedShareSheetEmbedVideoContentQuery_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="9702573803157362"}),null);
__d("CometUnifiedShareSheetEmbedVideoContentQuery$Parameters",["CometUnifiedShareSheetEmbedVideoContentQuery_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("CometUnifiedShareSheetEmbedVideoContentQuery_facebookRelayOperation"),metadata:{},name:"CometUnifiedShareSheetEmbedVideoContentQuery",operationKind:"query",text:null}};a.exports=e}),null);
__d("CometEmbedVideoDialog.entrypoint",["CometUnifiedShareSheetEmbedVideoContentQuery$Parameters","JSResourceForInteraction"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){var e=t.videoID;return{extraProps:{videoID:e},queries:{embedVideoQueryReference:{parameters:n("CometUnifiedShareSheetEmbedVideoContentQuery$Parameters"),variables:{videoID:e}}}}},root:r("JSResourceForInteraction")("CometEmbedVideoDialogRoot.react").__setRef("CometEmbedVideoDialog.entrypoint")};l.default=e}),98);
__d("CometFeedStoryMenuOriginalStoryIDContext",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.createContext(null);l.default=u}),98);
__d("CometPoliticalInfosheetDialogV2Query_facebookRelayOperation",[],(function(t,n,r,o,a,i){a.exports="25497284266566687"}),null);
__d("CometPoliticalInfosheetDialogV2Query$Parameters",["CometPoliticalInfosheetDialogV2Query_facebookRelayOperation"],(function(t,n,r,o,a,i){"use strict";var e={kind:"PreloadableConcreteRequest",params:{id:n("CometPoliticalInfosheetDialogV2Query_facebookRelayOperation"),metadata:{},name:"CometPoliticalInfosheetDialogV2Query",operationKind:"query",text:null}};a.exports=e}),null);
__d("CometPoliticalInfosheetDialogV2.entrypoint",["CometPoliticalInfosheetDialogV2Query$Parameters","JSResourceForInteraction","WebPixelRatio"],(function(t,n,r,o,a,i,l){"use strict";var e={getPreloadProps:function(t){var e=t.ad_id,n=t.story_id;return{queries:{politicalInfosheetQueryReference:{parameters:r("CometPoliticalInfosheetDialogV2Query$Parameters"),variables:{ad_id:e,entrypoint:"COMET_BACKEND",scale:o("WebPixelRatio").get(),story_id:n}}}}},root:r("JSResourceForInteraction")("CometPoliticalInfosheetDialogV2.react").__setRef("CometPoliticalInfosheetDialogV2.entrypoint")};l.default=e}),98);
__d("FBNucleusTranslateOutline20Icon.react",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react"));function u(e){return s.jsxs("svg",babelHelpers.extends({viewBox:"0 0 20 20",width:"1em",height:"1em",fill:"currentColor"},e,{children:[e.title!=null&&s.jsx("title",{children:e.title}),e.children!=null&&s.jsx("defs",{children:e.children}),s.jsx("path",{d:"M7.25 1.25a.75.75 0 0 0-1.5 0V2.5h-4a.75.75 0 1 0 0 1.5h.605l.237.907a12.332 12.332 0 0 0 2.826 5.207 10.83 10.83 0 0 1-3.413 1.927.75.75 0 0 0 .49 1.418A12.33 12.33 0 0 0 6.5 11.163c.533.457 1.106.87 1.713 1.231a.75.75 0 1 0 .769-1.288 10.842 10.842 0 0 1-1.4-.992 12.331 12.331 0 0 0 2.827-5.207L10.645 4h.605a.75.75 0 0 0 0-1.5h-4V1.25zM9.095 4l-.138.529A10.832 10.832 0 0 1 6.5 9.074 10.832 10.832 0 0 1 4.043 4.53L3.905 4h5.19zm7.436 12 1.024 2.531a.75.75 0 1 0 1.39-.562L14.613 7.251c-.405-1-1.82-1-2.225 0L8.055 17.97a.75.75 0 1 0 1.39.562L10.47 16h6.061zm-.606-1.5h-4.85L13.5 8.501l2.425 5.999z"})]}))}u.displayName=u.name+" [from "+i.id+"]",u._size=20,u._isSVG=!0;var c=u;l.default=c}),98);
__d("FDSArrowsSquareAddFilled24Icon",["cr:14443"],(function(t,n,r,o,a,i,l){"use strict";l.default=n("cr:14443")}),98);
__d("groupsCometDeleteNodeFromConnection",["CometRelay","RelayFBConnectionHandler"],(function(t,n,r,o,a,i,l){"use strict";function e(e,t,n,r){var a,i=e.get(t);i!=null&&((a=o("RelayFBConnectionHandler").getAllConnectionsWithKey(e,i,r))!=null?a:[]).forEach(function(e){return o("CometRelay").ConnectionHandler.deleteNode(e,n)})}l.default=e}),98);
__d("viewerContentUpdaterUtils",["CometRelay"],(function(t,n,r,o,a,i,l){"use strict";function e(e,t,n,r){var a=e.get(t);if(a!=null){var i;r==="PENDING"?i=o("CometRelay").ConnectionHandler.getConnection(n,"GroupsCometViewerContentPendingPostsFeed_stories",{content_type:r,ordering:"NEWEST_FIRST"}):r==="PUBLISHED"&&(i=o("CometRelay").ConnectionHandler.getConnection(n,"GroupsCometViewerContentPublishedPostsFeed_stories",{content_type:r,ordering:"NEWEST_FIRST"})),i!=null&&o("CometRelay").ConnectionHandler.insertEdgeBefore(i,a)}}function s(e,t,n){var r,o=t.getDataID(),a=(r=e.get(o))==null?void 0:r.getLinkedRecord("stories",{content_type:n});if(a!=null){var i=a.getDataID(),l=e.get(i);if(l!=null){var s=l.getValue("count_up_to",{max:51});typeof s=="number"&&l.setValue(Math.max(s-1,0),"count_up_to",{max:51});var u=l.getValue("count_up_to",{max:1});typeof u=="number"&&typeof s=="number"&&s-1===0&&l.setValue(Math.max(u-1,0),"count_up_to",{max:1})}}}l.addEdgeToViewerContentConnection=e,l.decrementSectionCounts=s}),98);
__d("viewerContentPendingPostUpdater",["CometRelay","groupsCometDeleteNodeFromConnection","viewerContentUpdaterUtils"],(function(t,n,r,o,a,i,l){"use strict";function e(e){var t=e.groupID,n=e.store,a=e.storyID;if(t!=null){var i=n.get(t);if(i!=null){var l=i.getLinkedRecord("viewer_content");if(l!=null){var s=l.getDataID();r("groupsCometDeleteNodeFromConnection")(n,s,a,"GroupsCometViewerContentPendingPostsFeed_stories"),o("viewerContentUpdaterUtils").decrementSectionCounts(n,l,"PENDING")}}}}function s(e,t){return function(n){if(t!=null){var r=n.get(e);if(r!=null){var a=r.getLinkedRecord("viewer_content");if(a!=null){var i=o("CometRelay").ConnectionHandler.getConnection(a,"GroupsCometViewerContentPendingPostsFeed_stories",{content_type:"PENDING",ordering:"NEWEST_FIRST"});i!=null&&o("CometRelay").ConnectionHandler.insertEdgeBefore(i,t)}}}}}l.viewerContentDeletePendingPostUpdater=e,l.viewerContentAddPendingPostUpdater=s}),98);