;/*FB_PKG_DELIM*/

__d("BrandSafetyEnforcementUtils",[],(function(t,n,r,o,a,i,l){"use strict";function e(e,t,n){return e===5&&n!=null&&t!=null&&n>t}l.isInvalidBrandSafetyPositioning=e}),98);
__d("CometBrandSafety",["react","react-compiler-runtime"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.useEffect,c=s.useRef;function d(e,t,n,r){var a=o("react-compiler-runtime").c(11),i;a[0]!==e||a[1]!==t||a[2]!==n||a[3]!==r?(i={hasMore:e,isEOFError:t,isLoading:n,showEOFMessageAfterFeedStoppedLoading:r},a[0]=e,a[1]=t,a[2]=n,a[3]=r,a[4]=i):i=a[4];var l=c(i),s,d;return a[5]!==e||a[6]!==t||a[7]!==n||a[8]!==r?(s=function(){l.current={hasMore:e,isEOFError:t,isLoading:n,showEOFMessageAfterFeedStoppedLoading:r}},d=[e,t,n,r],a[5]=e,a[6]=t,a[7]=n,a[8]=r,a[9]=s,a[10]=d):(s=a[9],d=a[10]),u(s,d),l}l.useCometBrandSafetyFeedStateInfo=d}),98);
__d("FBUnifiedVideoBakedInTextContext",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.createContext({isBakedInTextEnabled:!1,setIsBakedInTextEnabled:function(){}});l.default=u}),98);
__d("FBUnifiedVideoMuteContextProvider",["CometRouteRenderType","FBUnifiedVideoMuteContext","FBUnifiedVideoMuteContextDefaultValue","react","react-compiler-runtime","vulture"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=e,c=u.useContext,d=u.useMemo,m=u.useState;function p(e){var t=o("react-compiler-runtime").c(5),n=e.children;r("vulture")("B17h19uMbNyB0RNoM4XahRJGCLw=");var a=o("CometRouteRenderType").useIsPushView(),i=m(!a),l=i[0],u=i[1],c;t[0]!==l?(c={isMuted:l,setMute:u},t[0]=l,t[1]=c):c=t[1];var d=c,p;return t[2]!==n||t[3]!==d?(p=s.jsx(r("FBUnifiedVideoMuteContext").Provider,{value:d,children:n}),t[2]=n,t[3]=d,t[4]=p):p=t[4],p}function _(e){var t=o("react-compiler-runtime").c(5),n=e.children,a=e.shouldUseParentContext,i=c(r("FBUnifiedVideoMuteContext")),l;return t[0]!==n||t[1]!==i||t[2]!==e||t[3]!==a?(l=a===!0&&i!==r("FBUnifiedVideoMuteContextDefaultValue")?n:s.jsx(p,babelHelpers.extends({},e)),t[0]=n,t[1]=i,t[2]=e,t[3]=a,t[4]=l):l=t[4],l}l.default=_}),98);
__d("ReelsFeedbackDataNullabilitySettingContext",["react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=e||(e=o("react")),u=s.createContext({isDataOptional:!1});l.default=u}),98);
__d("XCometProfileContentInsightsControllerRouteBuilder",["jsRouteBuilder"],(function(t,n,r,o,a,i,l){var e=r("jsRouteBuilder")("/content/insights/",Object.freeze({}),void 0),s=e;l.default=s}),98);
__d("useFBReelsProcessRoute",["CometRouteParams","GlobalVideoPortsID","react-compiler-runtime","useRoutePassthroughProps","useSetVideoShareDownstreamSignalTracking","uuidv4"],(function(t,n,r,o,a,i,l){"use strict";function e(){var e=o("react-compiler-runtime").c(26),t=o("CometRouteParams").useRouteParams(),n=r("useRoutePassthroughProps")()||{},a=typeof t.video_id=="string"?t.video_id:"",i=typeof t.hide_next=="boolean"?t.hide_next:!1,l=typeof t.page_id=="string"?t.page_id:"",s=typeof n.trackingString=="string"?n.trackingString:"",u=typeof n.rootVideoTrackingKey=="string"?n.rootVideoTrackingKey:"",c=typeof n.rootVideoEncryptedTrackingKey=="string"?n.rootVideoEncryptedTrackingKey:"",d=typeof n.rootVideoClickTrackingLinkshimCb=="string"?n.rootVideoClickTrackingLinkshimCb:"",m=typeof n.rootVideoEncryptedClickTracking=="string"?n.rootVideoEncryptedClickTracking:"",p=typeof n.rootVideoID=="string"?n.rootVideoID:a,_;e[0]!==n.portableVideoID?(_=n.portableVideoID!=null&&typeof n.portableVideoID=="string"?o("GlobalVideoPortsID").ensureVideoID(n.portableVideoID):null,e[0]=n.portableVideoID,e[1]=_):_=e[1];var f=_,g=typeof t.group_id=="string"?t.group_id:null,h=n.entrypoint!=null?n.entrypoint:null,y="";typeof t.s=="string"?y=t.s:typeof n.s=="string"&&(y=n.s);var C;e[2]!==n.sessionID?(C=typeof n.sessionID=="string"?n.sessionID:r("uuidv4")(),e[2]=n.sessionID,e[3]=C):C=e[3];var b=C,v=!n.showComments,S=typeof n.isMuted=="boolean"?n.isMuted:null,R=typeof n.index=="number"?n.index:null,L=n.paginationFragment,E=n.paginationFragmentKey,k;e[4]!==a?(k=function(t){return a!=null&&a.length>0},e[4]=a,e[5]=k):k=e[5],r("useSetVideoShareDownstreamSignalTracking")(k);var I;return e[6]!==R||e[7]!==L||e[8]!==E||e[9]!==h||e[10]!==g||e[11]!==v||e[12]!==S||e[13]!==i||e[14]!==l||e[15]!==f||e[16]!==d||e[17]!==m||e[18]!==c||e[19]!==p||e[20]!==u||e[21]!==y||e[22]!==s||e[23]!==a||e[24]!==b?(I={aggregationPageNodeIndex:R,aggregationPaginationFragment:L,aggregationPaginationFragmentKey:E,entrypoint:h,groupID:g,isFullScreen:v,isMutedFromPreviousRoute:S,isNextButtonHidden:i,pageID:l,portableVideoID:f,rootVideoClickTrackingLinkshimCb:d,rootVideoEncryptedClickTracking:m,rootVideoEncryptedTrackingKey:c,rootVideoID:p,rootVideoTrackingKey:u,source:y,trackingString:s,videoID:a,viewerSessionID:b},e[6]=R,e[7]=L,e[8]=E,e[9]=h,e[10]=g,e[11]=v,e[12]=S,e[13]=i,e[14]=l,e[15]=f,e[16]=d,e[17]=m,e[18]=c,e[19]=p,e[20]=u,e[21]=y,e[22]=s,e[23]=a,e[24]=b,e[25]=I):I=e[25],I}l.default=e}),98);
__d("useFBUnifiedVideoBakedInTextContext",["FBUnifiedVideoBakedInTextContext","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=(e||(e=o("react"))).useContext;function u(){var e=s(r("FBUnifiedVideoBakedInTextContext"));return e}l.default=u}),98);
__d("useReelsFeedbackDataNullabilitySetting",["ReelsFeedbackDataNullabilitySettingContext","react"],(function(t,n,r,o,a,i,l){"use strict";var e,s=(e||(e=o("react"))).useContext;function u(){return s(r("ReelsFeedbackDataNullabilitySettingContext")).isDataOptional}l.default=u}),98);