;/*FB_PKG_DELIM*/

__d("ConcordFbUserClickEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("6163"),s=o("FalcoLoggerInternal").create("concord_fb_user_click_event",e),u=s;l.default=u}),98);
__d("ConcordFbUserSharingImpressionsEventFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("6244"),s=o("FalcoLoggerInternal").create("concord_fb_user_sharing_impressions_event",e),u=s;l.default=u}),98);
__d("FanFundingClientEventsFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("6478"),s=o("FalcoLoggerInternal").create("fan_funding_client_events",e),u=s;l.default=u}),98);
__d("FbOriginalAttributionFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("6853"),s=o("FalcoLoggerInternal").create("fb_original_attribution",e),u=s;l.default=u}),98);
__d("FbShortsAggregationPageClickedFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("1435"),s=o("FalcoLoggerInternal").create("fb_shorts_aggregation_page_clicked",e),u=s;l.default=u}),98);
__d("FbShortsInstagramDeeplinkFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("1518"),s=o("FalcoLoggerInternal").create("fb_shorts_instagram_deeplink",e),u=s;l.default=u}),98);
__d("FbShortsSaveReelFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("2035"),s=o("FalcoLoggerInternal").create("fb_shorts_save_reel",e),u=s;l.default=u}),98);
__d("FbShortsSeeLessFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("1490"),s=o("FalcoLoggerInternal").create("fb_shorts_see_less",e),u=s;l.default=u}),98);
__d("FbShortsUndoSeeLessFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("1491"),s=o("FalcoLoggerInternal").create("fb_shorts_undo_see_less",e),u=s;l.default=u}),98);
__d("FbShortsVideoDescriptionClickFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("1561"),s=o("FalcoLoggerInternal").create("fb_shorts_video_description_click",e),u=s;l.default=u}),98);
__d("FbShortsViewerOpenFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("936"),s=o("FalcoLoggerInternal").create("fb_shorts_viewer_open",e),u=s;l.default=u}),98);
__d("ProfilePlusBoostEventsFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("2791"),s=o("FalcoLoggerInternal").create("profile_plus_boost_events",e),u=s;l.default=u}),98);
__d("SfvChainingNavigationExitFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("694"),s=o("FalcoLoggerInternal").create("sfv_chaining_navigation_exit",e),u=s;l.default=u}),98);
__d("SfvChainingNavigationScrollFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("1465"),s=o("FalcoLoggerInternal").create("sfv_chaining_navigation_scroll",e),u=s;l.default=u}),98);
__d("SfvChainingVpvdFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("1443"),s=o("FalcoLoggerInternal").create("sfv_chaining_vpvd",e),u=s;l.default=u}),98);
__d("ShortsFollowFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("1495"),s=o("FalcoLoggerInternal").create("shorts_follow",e),u=s;l.default=u}),98);
__d("ShortsTapCreatorProfileFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("1300"),s=o("FalcoLoggerInternal").create("shorts_tap_creator_profile",e),u=s;l.default=u}),98);
__d("ShortsUnfollowFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(t,n,r,o,a,i,l){"use strict";var e=r("getFalcoLogPolicy_DO_NOT_USE")("1496"),s=o("FalcoLoggerInternal").create("shorts_unfollow",e),u=s;l.default=u}),98);